name: Lint GitHub Actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    paths:
      - ".github/workflows/**"

# Security: Set minimal permissions
permissions:
  contents: read

jobs:
  actionlint:
    name: Lint Actions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Run actionlint
        uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
        with:
          reporter: github-pr-review
          fail_on_error: true
          level: error