name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Security: Set minimal permissions
permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Build Binary for Tests
        run: go build -o antidot-home .

      - name: Run Tests
        run: go test -json ./... > test_results.json

      - name: Annotate Tests
        if: always()
        uses: guyarb/golang-test-annotations@2941118d7ef622b1b3771d1ff6eae9e90659eb26 # v0.8.0
        with:
          test-results: test_results.json
